config/routes.rb
Rails.application.routes.draw do
  get 'user/new'

  root 'top#index'

  get 'login' => 'session#new'
  post 'login' => 'session#new'
  #get "change_password", :to => "user/passwords#edit"
  get "forget_password", :to => "session#forget_password"
  post "forget_password", :to => "session#forget_password"
  post 'signin' => 'session#create'
  get 'signin' => 'session#create'
  get 'logout' => 'session#destroy'

  get "session/get_verification", to: "session#get_verification"

  get "home", to: "home#index"
  post "home/upload_image", to: "home#upload_image"
  get "home/edit", to: "home#edit"
  post "home/edit", to: "home#edit"

  get "home/post/list", to: "home/post#list"
  post "home/post/list", to: "home/post#list"
  get "home/post/new", to: "home/post#new"
  post "home/post/new", to: "home/post#new"
  get "home/post/new/:id", to: "home/post#new", as: :home_post_edit
  post "home/post/new/:id", to: "home/post#new"
  post "home/post/change_flag/:id", to: "home/post#change_flag"
  delete "home/post/delete/:id", to: "home/post#delete", as: :home_post_delete
  post "home/post/upload_image", to: "home/post#upload_image"

  get "home/activity/list", to: "home/activity#list"
  post "home/activity/list", to: "home/activity#list"
  get "home/activity/new", to: "home/activity#new"
  post "home/activity/new", to: "home/activity#new"
  get "home/activity/new/:id", to: "home/activity#new", as: :home_activity_edit
  post "home/activity/new/:id", to: "home/activity#new"
  post "home/activity/upload_image", to: "home/activity#upload_image"

  get "/activity/:id", to: "activity#show", as: :activity
  post "/activity/join", to: "activity#join"

  get "home/brand/new", to: "home/brand#new", as: :new_brand
  post "home/brand/new", to: "home/brand#new"
  get "home/brand/:type", to: "home/brand#list", as: :list_brand
  get "home/brand/operate/:brand_id/:type", to: "home/brand#operate", as: :operate_brand

  post '/home/upload/create', to: 'home/upload#create'
  post '/home/upload/:id/update', to: 'home/upload#update', :constraints => {:id => /\d+/}

  get "/post/:id", to: "post#show", as: :post

  get "/favorite/:id", to: "home#favorite", as: :favorite

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  #http://www.jianshu.com/p/c525e4c18f5a
  def new
    @head_title = "登录"
    if !params[:session].nil? && !params[:session][:phone].blank?
      user = User.find_by(phone: params[:session][:phone])
      if user && BCrypt::Password.new(user.password_digest) == params[:session][:password]
        log_in(user) #SessionsHelper中的方法
        #判断是否要持续性的记住用户的登录状态
        params[:session][:remeber_me] == "1" ? remeber(user) : forget(user)
        redirect_to home_path
      else
        flash[:notice] = "密码或者手机号不对"
      end

    end
  end

  def create
    @head_title = "注册"
    if !params[:session].nil? && !params[:session][:verification_code].blank? && !params[:session][:phone].blank?
      user = User.find_by(phone: params[:session][:phone])
      if !user.nil?
        if user.is_verify?
          flash[:notice] = "用户已经注册成功"
        else
          if BCrypt::Password.new(user.verification_digest) == params[:session][:verification_code] && user.verification_time >= 20.minutes.ago
            user.password_digest = BCrypt::Password.create(params[:session][:password])
            user.is_verify = 1
            user.save
            log_in(user) #SessionsHelper中的方法
            redirect_to home_path
          else
            flash[:notice] = "验证码超时"
          end
        end
      else
        flash[:notice] = "验证码验证失败"
      end
    end
  end

  def get_verification
    phone_match = params[:phone].match(/^1[3|4|5|8][0-9]\d{4,8}$/)
    if phone_match.nil?
      return render json: {value: "电话号码异常", status: 0}
    end
    user = User.find_by(phone: params[:phone])
    if user.nil?
      user = User.new
      user.phone = params[:phone]
    else
      if user.is_verify?
        flash[:notice] = "用户已经注册成功"
      else
        if user.verification_time.to_date == Date.today
          return render json: {value: "已经验证超过三次了，明天继续", status: 3} if user.verification_limit > 2
        else
          user.verification_limit = 0
        end
      end
    end
    user.verification_limit += 1
    verification_code = rand(1000..9999)
    user.verification_digest = BCrypt::Password.create(verification_code)
    user.verification_time = Time.now
    user.save
    UserProfile.create(user_id: user.id, user_name: user.phone)
    return render json: {value: verification_code, status: 1}
  end

  def forget_password
    @head_title = "重置密码"
    if !params[:session].nil? && !params[:session][:verification_code].blank? && !params[:session][:phone].blank?
      user = User.find_by(phone: params[:session][:phone])
      p user
      if !user.nil?
        p user.verification_time
        p 20.minutes.ago
        if BCrypt::Password.new(user.verification_digest) == params[:session][:verification_code] && user.verification_time >= 20.minutes.ago
          user.password_digest = BCrypt::Password.create(params[:session][:password])
          user.is_verify = 1
          user.save
          log_in(user) #SessionsHelper中的方法
          p current_user
          redirect_to home_path
        else
          flash[:notice] = "验证码超时"
        end
      else
        flash[:notice] = "验证码不能匹配,请重新匹配"
      end
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/session_helper.rb
module SessionHelper
  #一旦账号密码正确，则成功登录，同时在session中记录session[:user_id]
  def log_in(user)
    session[:user_id] = user.id
    cookies.signed[:user_info] = {value:user.id}
    user.login_at = Time.now.to_s(:db)
    user.ip = request.remote_ip
    user.save
  end
  #如果用户允许在本地保存登录信息，则保存cookies
  def remeber(user)
    #先把本次登录的remeber_token保存至数据库
    user.remeber
    #然后把remeber_token保存到cookies中，同时把user_id也保存在cookies中
    # cookies[:remeber_token] = { value: user.remeber_token, expires: 5.minutes.from_now.utc}
    # cookies.signed[:user_id] = { value: user.id, expires: 5.minutes.from_now.utc}
    cookies.permanent[:remeber_token] = user.remeber_token
    cookies.permanent.signed[:user_id] = user.id
  end

  #获取当前登录用户，如未登录，则为nil.@current_user这个实例变量是为了避免每次调用current_user方法都去查询一遍数据库的情况。
  def current_user
    #先判断session中是否为nil
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
      #再判断cookies中是否保存了登录信息
    else (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      #如果cookies中保存了，再用authenticated?这个方法判断cookies[:remeber_token]或者数据库中的remeber_digest是否一致。
      if user && user.authenticated?(cookies[:remeber_token])
        log_in(user)
        @current_user = user
      end
    end
  end

  #用来判断用户是否登录的方法
  def logged_in?
    !current_user.nil?
  end

  #用来清空持久性登录信息
  def forget(user)
    user.forget #将user.remeber_digest重置为nil
    #删除cookies中的登录信息
    cookies.delete(:user_id)
    cookies.delete(:remeber_token)
  end

  #退出，同时删除session中的信息
  def log_out
    forget(current_user)
    session.delete(:user_id)
    cookies.delete(:user_info)
    @current_user = nil
  end

end

app/views/session/create.html.erb
<div class="md_card">
  <div class="md_box">
    <%=form_for :session, url: signin_path, method: "post", html: {id: "signinForm"} do |f|%>
        <div class="box_text mb20">
          <%=f.text_field :phone, class: "text", placeholder: "输入手机号"%>
        </div>

        <div class="box_text code mb20">
          <%=f.text_field :verification_code, autocomplete: "off", class: "text", size: "6"%>
        </div>
        <div class="sms-code">
          <span class="confirm_a" onclick="getVerificationCode()" time="60" id="verification_code_btn">获得验证码</span>
        </div>
        <div class="box_text mb20">
          <%= f.password_field :password, autocomplete: "off", class: "text", placeholder: "密码（字母，数字，至少6位）"%>
        </div>
        <div class="box_text mb20">
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "text", placeholder: "再次输入密码"%>
        </div>
        <div class="confirm_area">
          <span onclick="submitSignIn()" class="confirm_a">注册</span>
        </div>
    <%end%>
    <div class="line"></div>
    <div class="mt20 tec">
      已有帐号？<%= link_to "立即登陆", login_path %>
    </div>
  </div>
</div>


<%=flash[:notice] if !params[:session].blank?%>

app/views/session/forget_password.html.erb
<div class="md_card">
  <div class="md_box">
    <%=form_for :session, url: forget_password_path, method: "post" do |f|%>
    <div class="box_text mb20">
      <%=f.text_field :phone, class: "text", placeholder: "输入手机号", size: "30"%>
    </div>
    <!--账号输入为空时-->
    <!--<div class="error-block">
      <span class="icon icon-warning"></span><span class="error-block-message">请输入邮箱或手机号码</span>
    </div>-->
    <!--账号输入错误时-->
    <!--<div class="error-block">
      <span class="icon icon-warning"></span><span class="error-block-message">请输入正确的邮箱或手机号码</span>
    </div>-->
    <div class="box_text code mb20">
      <%=f.text_field :verification_code, autocomplete: "off", class: "text"%>
    </div>
    <div class="sms-code">
      <span class="confirm_a" onclick="getVerificationCode()" time="60" id="verification_code_btn">获得验证码</span>
    </div>
    <!--验证码未输入时-->
    <!--<div class="error-block">
      <span class="icon icon-warning"></span><span class="error-block-message">请输入验证码</span>
    </div>-->
    <!--验证码输入有误时-->
    <!--<div class="error-block">
     <span class="icon icon-warning"></span><span class="error-block-message">请输入正确的验证码</span>
   </div>-->

    <div class="box_text mb20">
      <%= f.password_field :password, autocomplete: "off", class: "text", placeholder: "新密码"%>
    </div>

    <div class="box_text mb20">
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "text", placeholder: "再次输入密码"%>
    </div>
    <!--新密码输入为空时-->
    <!--<div class="error-block">
      <span class="icon icon-warning"></span><span class="error-block-message">请输入新密码</span>
    </div>-->
    <!--确认密码输入为空时-->
    <!--<div class="error-block">
      <span class="icon icon-warning"></span><span class="error-block-message">请输入确认密码</span>
    </div>-->
    <!--密码输入不一致时-->
    <!--<div class="error-block">
      <span class="icon icon-warning"></span><span class="error-block-message">密码输入不一致</span>
    </div>-->
    <!--密码输入超长时-->
    <!--<div class="error-block">
      <span class="icon icon-warning"></span><span class="error-block-message">请输入20字符以内密码</span>
    </div>-->
    <div class="confirm_area">
      <span class="confirm_a" onclick="submitSignIn()">重置密码</span>
    </div>
    <%end%>
  </div>
</div>

<%=flash[:notice] if !params[:session].blank?%>

app/views/session/new.html.erb
<div class="md_card">
  <div class="md_box">
    <%=form_for :session, url: login_path, method: "post" do |f|%>
    <div class="box_text mb20">
      <%=f.text_field :phone, class: "text", placeholder: "输入手机号"%>
    </div>
    <div class="box_text mb10">
      <%= f.password_field :password, autocomplete: "off", class: "text", placeholder: "密码" %>
    </div>
    <div class="box_text mb20">
      <label><input name="" type="hidden" value="0"><input type="checkbox" value=""> 自动登录</label>
      <%= link_to "忘记密码?", forget_password_path , class: "fr"%>
    </div>
    <div class="confirm_area">
      <span class="confirm_a" onclick="submitLogin()">登录</span>
    </div>
    <div class="line"></div>
    <div class="mt20 tec">
      还没有帐号？<%= link_to "注册新帐号", signin_path %>
    </div>
    <%end%>
  </div>
</div>

<%=flash[:notice] if !params[:session].blank?%>