config/routes.rb
Rails.application.routes.draw do
  get 'user/new'

  root 'top#index'

  get 'login' => 'session#new'
  post 'login' => 'session#new'
  #get "change_password", :to => "user/passwords#edit"
  get "forget_password", :to => "session#forget_password"
  post "forget_password", :to => "session#forget_password"
  post 'signin' => 'session#create'
  get 'signin' => 'session#create'
  get 'logout' => 'session#destroy'

  get "session/get_verification", to: "session#get_verification"

  get "home", to: "home#index"
  post "home/upload_image", to: "home#upload_image"
  get "home/edit", to: "home#edit"
  post "home/edit", to: "home#edit"

  get "home/post/list", to: "home/post#list"
  post "home/post/list", to: "home/post#list"
  get "home/post/new", to: "home/post#new"
  post "home/post/new", to: "home/post#new"
  get "home/post/new/:id", to: "home/post#new", as: :home_post_edit
  post "home/post/new/:id", to: "home/post#new"
  post "home/post/change_flag/:id", to: "home/post#change_flag"
  delete "home/post/delete/:id", to: "home/post#delete", as: :home_post_delete
  post "home/post/upload_image", to: "home/post#upload_image"

  get "home/activity/list", to: "home/activity#list"
  post "home/activity/list", to: "home/activity#list"
  get "home/activity/new", to: "home/activity#new"
  post "home/activity/new", to: "home/activity#new"
  get "home/activity/new/:id", to: "home/activity#new", as: :home_activity_edit
  post "home/activity/new/:id", to: "home/activity#new"
  post "home/activity/upload_image", to: "home/activity#upload_image"

  get "/activity/:id", to: "activity#show", as: :activity
  post "/activity/join", to: "activity#join"

  get "home/brand/new", to: "home/brand#new", as: :new_brand
  post "home/brand/new", to: "home/brand#new"
  get "home/brand/:type", to: "home/brand#list", as: :list_brand
  get "home/brand/operate/:brand_id/:type", to: "home/brand#operate", as: :operate_brand

  post '/home/upload/create', to: 'home/upload#create'
  post '/home/upload/:id/update', to: 'home/upload#update', :constraints => {:id => /\d+/}

  get "/post/:id", to: "post#show", as: :post

  get "/favorite/:id", to: "home#favorite", as: :favorite

end

app/controllers/home/activity_controller.rb
class Home::ActivityController < HomeController

  def index

  end

  def list
    @head_title = "我的活动"
    @activities = Activity.where(user_id: current_user.id, check_flag: Activity::EDIT_FLAG)
  end

  def new
    if params[:id].blank?
      @head_title = "新建活动"
      @activity = Activity.find_or_create_by(check_flag: Activity::NEW_FLAG, user_id: current_user.id)
    else
      @head_title = "编辑活动"
      @activity = Activity.find_by(id: params[:id])
    end
    @show_address_flag = true
    # @brands = Brand.all
    if request.post?
      @activity.attributes = params.require(:activity).permit(:title, :phone, :start_time, :end_time, :province, :city, :district, :detail_address)
      @activity.check_flag = Activity::EDIT_FLAG
      if !@activity.valid?
        flash[:notice] = @activity.errors.full_messages
        p flash[:notice]
      else
        @activity.save
        return redirect_to home_activity_list_path
      end
    end
  end

  def delete
    post = Post.find_by(id: params[:id])
    post.delete
    return redirect_to home_list_path
  end

  def upload_image
    if params[:image_id].blank? || params[:activity_id].blank?
      set_json_error({message: "params error"})
    else
      activity = Activity.find_by(id: params[:activity_id])
      activity.attributes = params.require(:activity).permit(params[:image_id], "#{params[:image_id]}_file_name", "#{params[:image_id]}_content_type", "#{params[:image_id]}_file_size", "#{params[:image_id]}_updated_at")
      activity.try(params[:image_id]).reprocess!
      if activity.valid?
        activity.transaction do
          activity.save
        end
        set_json_success({url: activity.try(params[:image_id]).url(:medium)})
      else
        set_json_error({message: activity.errors.full_messages.join(",")})
      end
    end

    respond_to do |format|
      format.json { render_to_json }
    end
  end
end

app/controllers/home/brand_controller.rb
class Home::BrandController < HomeController

  before_action :check_login

  def new
    @brand = Brand.new

    if request.post?
      @brand.attributes = brand_form_params
      if @brand.valid?
        @brand.save
        UserBrand.create(user_id: current_user.id, brand_id: @brand.id)
        redirect_to controller: "/home/brand", action: "list", type: Brand::HAVE_BIND
      else
        p @brand.errors
      end
    end
  end

 ##品牌列表
  def list
    @type = params[:type].blank? ? Brand::HAVE_BIND : params[:type].to_i
    @brands = Brand.get_brands(current_user.id, @type)
  end

  ##绑定品牌
  def operate
    data = {status: -1}
    if request.xhr?
      brand_id = params[:brand_id]
      user_id = current_user.id
      type = params[:type]

      max_count = 20

      user_brand = UserBrand.where(user_id: user_id, brand_id: brand_id).first
      ##解除绑定 type=1
      if type.to_i == Brand::HAVE_BIND
        if user_brand.blank?
          data[:status] = -1 ##解除失败
        else
          user_brand.destroy
          data[:status] = 1 ##解除成功
        end
      else
        if user_brand.blank?
          count = UserBrand.where(user_id: user_id, brand_id: brand_id).count
          if count < max_count
            user_brand = UserBrand.create(user_id: user_id, brand_id: brand_id)
            data[:status] = 2 ##绑定成功
          else
            data[:status] = 0 ##绑定失败，超过数目
          end
        else
          data[:status] = -1 ##绑定失败
        end
      end
    end
    return render_to_json(data)
  end


  def brand_form_params
    params.require(:brand)
        .permit(:user_id,
                :name,
                :logo,
                :brand_category_id,
                :province,
                :city,
                :district,
                :detail_address,
                :leader,
                :tel,
                :licence,
                :business_scope,
                :content
        )
  end
  private :brand_form_params

end

app/controllers/home/post_controller.rb
class Home::PostController < HomeController

  def index

  end

  def list
    @head_title = "我的展示"
    @posts = Post.where(check_flag: Post::EDIT_FLAG, user_id: current_user.id)
  end

  def new
    if params[:id].blank?
      @head_title = "新建活动"
      @post = Post.find_or_create_by(check_flag: Post::NEW_FLAG, user_id: current_user.id)
    else
      @head_title = "编辑活动"
      @post = Post.find_by(id: params[:id])
    end
    @brands = UserBrand.includes(:brand).where(user_id: current_user.id).map(&:brand)
    if request.post?
      @post.attributes = params.require(:post).permit(:title, :building, :province, :city, :district, :detail_address, :room_cnt, :living_room_cnt, :toilet_cnt, :kitchen_cnt, :home_size, :content1, :content2, :content3, :brand_ids)
      @post.check_flag = Post::EDIT_FLAG
      if !@post.valid?
        flash[:notice] = @post.errors.full_messages
        p flash[:notice]
      else
        @post.save
        return redirect_to home_post_list_path
      end
    end
  end

  def change_flag

  end

  def delete
    post = Post.find_by(id: params[:id], user_id: current_user.id)
    post.delete
    return redirect_to home_post_list_path
  end

  def upload_image
    if params[:image_id].blank? || params[:post_id].blank?
      set_json_error({message: "params error"})
    else
      post = Post.find_by(id: params[:post_id])
      post.attributes = params.require(:post).permit(params[:image_id], "#{params[:image_id]}_file_name", "#{params[:image_id]}_content_type", "#{params[:image_id]}_file_size", "#{params[:image_id]}_updated_at")
      post.try(params[:image_id]).reprocess!
      if post.valid?
        post.transaction do
          post.save
        end
        set_json_success({url: post.try(params[:image_id]).url(:medium)})
      else
        set_json_error({message: post.errors.full_messages.join(",")})
      end
    end

    respond_to do |format|
      format.json { render_to_json }
    end
  end
end

app/controllers/home/upload_controller.rb
class Home::UploadController < HomeController

  protect_from_forgery except: :create

  def create
    _style = params[:style].blank? ? 'original' : params[:style]
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.valid?
        @upload.save

        format.json { render :json => { url: @upload.image.url(_style), upload_id: @upload.id } }
      else
        format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
      end
    end
  end

  def update
    upload_id = params[:id]

    @upload = Upload.find_by_id(upload_id)

    if @upload.nil?
      @upload = Upload.new(upload_params)
      # format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
    else
      @upload.attributes = upload_params
      @upload.image.reprocess!
    end

    respond_to do |format|
      if @upload.valid?
        @upload.save
        format.json { render :json => { url: @upload.image.url(:original), upload_id: @upload.id } }
      else
        format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
      end
    end
  end

  # def create_avatar
  #   upload_type = params[:upload_type]
  #   blog_user_id = params[:id]
  #
  #   if upload_type == "blog_user" && blog_user_id.blank?
  #     blog_user_id = 0
  #   end
  #
  #   #获取Upload表存储存的文件ID
  #   blog_user = BlogUser.find_by_id(blog_user_id)
  #
  #   @upload = blog_user.get_avatar if !blog_user.blank?
  #
  #   if @upload.nil?
  #     @upload = Upload.new(upload_params)
  #     @upload.upload_type = upload_type
  #   else
  #     @upload.attributes = upload_params
  #     @upload.upload_type = upload_type
  #     @upload.image.reprocess!
  #   end
  #
  #   respond_to do |format|
  #     if @upload.valid?
  #       Upload.transaction do
  #         @upload.save
  #
  #         if !blog_user.blank?
  #           blog_user.avatar = @upload.id
  #           blog_user.save!
  #         end
  #       end
  #
  #       format.json { render :json => { url: @upload.image.url(:large), upload_id: @upload.id } }
  #     else
  #       format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
  #     end
  #   end
  # end

  private

  def upload_params
    params.require(:upload).permit(:image, :image_file_name, :image_content_type, :image_file_size, :image_updated_at, :md5, :upload_type)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_login#, except: :favorite

  def index
    @head_title = "我的页面"
  end

  def edit
    @head_title = "编辑"
    @user_profile = current_user.user_profile
    if request.post?
      @user_profile.attributes = params.require(:user_profile).permit(:user_name, :motto, :province, :city, :district, :detail_address)
      if !@user_profile.valid?
        flash[:notice] = @user_profile.errors.full_messages
        p flash[:notice]
      end
      @user_profile.save
    end
  end

  def upload_image
    up = UserProfile.find_by(user_id: current_user.id)

    up.attributes = params.require(:user_profile).permit(:avatar, :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at)
    up.avatar.reprocess!

    respond_to do |format|
      if up.valid?
        up.transaction do
          up.save
        end
        set_json_success({url: up.avatar.url(:medium)})
      else
        set_json_error({message: up.errors.full_messages.join(",")})
      end
      format.json { render_to_json }
    end
  end

  def favorite
    uf = UserFavorite.find_by(user_id: current_user.id, post_id: params[:id])
    if uf.nil?
      UserFavorite.create(user_id: current_user.id, post_id: params[:id])
      set_json_success({value: "add"})
    else
      uf.delete
      set_json_success({value: "delete"})
    end

    respond_to do |format|
      format.json { render_to_json }
    end
  end

  private
  def check_login
    if !logged_in?
      redirect_to login_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def show_post_btn(post)
    if post.is_edit?
      link_to "公开", {controller: "/home/post", action: "change_flag", id: post.id, flag: Post::PUB_FLAG}, remote: true
    elsif post.is_pub?
      link_to "私有", {controller: "/home/post", action: "change_flag", id: post.id, flag: Post::EDIT_FLAG}, remote: true
    end
  end
end

app/views/home/edit.html.erb
<div class="md_home">
  <div class="md_box" style="margin-bottom: 40px;">
    <%= form_for @user_profile, url: home_edit_path, method: "post" do |f|%>
    <div class="box_text mb20">
      <p>昵称</p>
      <%=f.text_field :user_name, class: "text"%>
    </div>

    <div class="box_text mb20">
      <p>简介</p>
      <%=f.text_area :motto, class: "text", maxlength: 100%>
    </div>

    <div class="update">
      <p>上传图像</p>
      <div class="clearfix">
        <div class="my_image" id="my_image">
          <%=image_tag current_user.user_profile.get_avatar_img("medium")%>
        </div>
        <div class="upload_form">
          <label>图片大小小于2兆</label>
          <%#= f.file_field :avatar %>
          <label for="upload_user_image">上传图片</label>
          <input type="file" id="upload_user_image" onchange="uploadUserImage(this)" style="display: none">
        </div>
      </div>
    </div>
    <div class="clearfix select_area">
      <p>工作所在地</p>
      <div data-toggle="distpicker">
        <%= f.select :province, {}, {}, {"data-province": @user_profile.province.blank?? '---- 选择省 ----': @user_profile.province}%>
        <%= f.select :city, {}, {}, {"data-city": @user_profile.city.blank?? '---- 选择市 ----': @user_profile.city}%>
        <%= f.select :district, {}, {}, {"data-district": @user_profile.district.blank?? '---- 选择区 ----': @user_profile.district}%>
      </div>
    </div>
    <div class="box_text mb20 detailed_address">
      <%= f.text_field :detail_address, placeholder: "详细地址", class: "text" %>
    </div>
    <div class="confirm_area">
      <span onclick="userEditorSubmit()" class="confirm_a">提交</span>
    </div>
    <%end%>
  </div>
</div>

app/views/home/index.html.erb
<div class="myhome">
  <!--用户头像／名字-->
  <div class="myhome_top">
    <%= link_to home_edit_path do%>
    <div class="info-avatar"><%=image_tag current_user.user_profile.get_avatar_img("medium")%></div>
    <div class="info-items is-bfc clearfix">
      <div class="info-name">
        <%=current_user.user_profile.try(:user_name)%>
        <div class="introduce">
          简介:<%=current_user.user_profile.get_motto%>
        </div>
      </div>
    </div>
    <%end%>
  </div>
  <div class="myhome_con">
    <ul class="user_slist">
      <li>
        <span class="icon-file-text2"></span>
        <%= link_to "我的资料", home_edit_url%>
        <span class="icon-chevron-thin-right"></span>
      </li>
      <li><span class="icon-file-picture"></span><%= link_to "我的展示", home_post_list_path%><span class="icon-chevron-thin-right"></span></li>
      <li><span class="icon-file-picture"></span><%= link_to "我的活动", home_activity_list_path%><span class="icon-chevron-thin-right"></span></li>
    </ul>
  </div>
  <div class="myhome_con">
    <ul class="user_slist">
      <li><span class="icon-clipboard"></span><%= link_to("登记品牌",new_brand_path)%><span class="icon-chevron-thin-right"></span></li>
      <li><span class="icon-paste"></span><%= link_to("绑定品牌",list_brand_path(1))%><span class="icon-chevron-thin-right"></span></li>
      <!-- 积分模块
       <li><span class="icon-gift"></span><a href="" class="">积分358</a><span class="icon-chevron-thin-right"></li>-->
      <li><span class="icon-paste"></span> <%=link_to("退出", logout_path, class: "logout")%><span class="icon-chevron-thin-right"></span></li>
    </ul>
  </div>
</div>