config/routes.rb
Rails.application.routes.draw do
  get 'user/new'

  root 'top#index'

  get 'login' => 'session#new'
  post 'login' => 'session#new'
  #get "change_password", :to => "user/passwords#edit"
  get "forget_password", :to => "session#forget_password"
  post "forget_password", :to => "session#forget_password"
  post 'signin' => 'session#create'
  get 'signin' => 'session#create'
  get 'logout' => 'session#destroy'

  get "session/get_verification", to: "session#get_verification"

  get "home", to: "home#index"
  post "home/upload_image", to: "home#upload_image"
  get "home/edit", to: "home#edit"
  post "home/edit", to: "home#edit"

  get "home/post/list", to: "home/post#list"
  post "home/post/list", to: "home/post#list"
  get "home/post/new", to: "home/post#new"
  post "home/post/new", to: "home/post#new"
  get "home/post/new/:id", to: "home/post#new", as: :home_post_edit
  post "home/post/new/:id", to: "home/post#new"
  post "home/post/change_flag/:id", to: "home/post#change_flag"
  delete "home/post/delete/:id", to: "home/post#delete", as: :home_post_delete
  post "home/post/upload_image", to: "home/post#upload_image"

  get "home/activity/list", to: "home/activity#list"
  post "home/activity/list", to: "home/activity#list"
  get "home/activity/new", to: "home/activity#new"
  post "home/activity/new", to: "home/activity#new"
  get "home/activity/new/:id", to: "home/activity#new", as: :home_activity_edit
  post "home/activity/new/:id", to: "home/activity#new"
  post "home/activity/upload_image", to: "home/activity#upload_image"

  get "/activity/:id", to: "activity#show", as: :activity
  post "/activity/join", to: "activity#join"

  get "home/brand/new", to: "home/brand#new", as: :new_brand
  post "home/brand/new", to: "home/brand#new"
  get "home/brand/:type", to: "home/brand#list", as: :list_brand
  get "home/brand/operate/:brand_id/:type", to: "home/brand#operate", as: :operate_brand

  post '/home/upload/create', to: 'home/upload#create'
  post '/home/upload/:id/update', to: 'home/upload#update', :constraints => {:id => /\d+/}

  get "/post/:id", to: "post#show", as: :post

  get "/favorite/:id", to: "home#favorite", as: :favorite

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user_profile, foreign_key: :user_id, primary_key: :user_id
  has_many :user_favorite
  has_many :activity_user

  # 新创建的一个,没有填任何内容
  NEW_FLAG = 0
  # 有内容, 为编辑状态
  EDIT_FLAG = 1
  # 完成状态
  PUB_FLAG = 2

  has_attached_file :avatar1,
                    styles: { large: "400x400#", medium: "200x200#", thumb: "100x100#" },
                    default_url: "upload_image.png",
                    path: 'public/activity_image/:id/avatar1/:hash.:extension',
                    url: '/activity_image/:id/avatar1/:hash.:extension',
                    hash_secret: "longSecretString"

  has_attached_file :avatar2,
                    styles: { large: "400x400#", medium: "200x200#", thumb: "100x100#" },
                    default_url: "upload_image.png",
                    path: 'public/activity_image/:id/avatar2/:hash.:extension',
                    url: '/activity_image/:id/avatar2/:hash.:extension',
                    hash_secret: "longSecretString"


  validates_attachment_content_type :avatar1, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_size :avatar1, less_than: 2.megabytes

  validates_attachment_content_type :avatar2, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_size :avatar2, less_than: 2.megabytes


  before_save :randomize_file_name

  def randomize_file_name
    unless avatar1_file_name.nil? || avatar1_file_name_changed?
      extension = File.extname(avatar1_file_name).downcase
      self.avatar1.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
    end
    unless avatar2_file_name.nil? || avatar2_file_name_changed?
      extension = File.extname(avatar2_file_name).downcase
      self.avatar2.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
    end
  end

  def get_avatar_img(style, image="avatar1")
    return self.try(image).url(style)
  end

  def check_img(image)
    ("upload_image.png" == self.try(image).url(:medium))? true:false
  end

  def get_address
    "#{self.province}#{self.city}#{self.district}#{self.detail_address}"
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController

  def show
    @show_join_activity_flag = true
    @activity = Activity.find_by(id: params[:id])
    @activity_user = ActivityUser.new
    @activity_user.activity_id = @activity.id
  end

  def join
    au_params = params.require(:activity_user).permit(:user_name, :activity_id, :phone)
    @activity = Activity.find_by(id: au_params[:activity_id])
    activity_u = ActivityUser.find_by(activity_id: au_params[:activity_id], phone: au_params[:phone])
    if activity_u.nil?
      ActivityUser.create(au_params)
      @show_message = {message: "报名成功!"}
    else
      @show_message = {message: "您已经报过名了!"}
    end

    respond_to do |format|
      format.js {return render :template => "activity/activity"}
    end
  end
end

app/controllers/home/activity_controller.rb
class Home::ActivityController < HomeController

  def index

  end

  def list
    @head_title = "我的活动"
    @activities = Activity.where(user_id: current_user.id, check_flag: Activity::EDIT_FLAG)
  end

  def new
    if params[:id].blank?
      @head_title = "新建活动"
      @activity = Activity.find_or_create_by(check_flag: Activity::NEW_FLAG, user_id: current_user.id)
    else
      @head_title = "编辑活动"
      @activity = Activity.find_by(id: params[:id])
    end
    @show_address_flag = true
    # @brands = Brand.all
    if request.post?
      @activity.attributes = params.require(:activity).permit(:title, :phone, :start_time, :end_time, :province, :city, :district, :detail_address)
      @activity.check_flag = Activity::EDIT_FLAG
      if !@activity.valid?
        flash[:notice] = @activity.errors.full_messages
        p flash[:notice]
      else
        @activity.save
        return redirect_to home_activity_list_path
      end
    end
  end

  def delete
    post = Post.find_by(id: params[:id])
    post.delete
    return redirect_to home_list_path
  end

  def upload_image
    if params[:image_id].blank? || params[:activity_id].blank?
      set_json_error({message: "params error"})
    else
      activity = Activity.find_by(id: params[:activity_id])
      activity.attributes = params.require(:activity).permit(params[:image_id], "#{params[:image_id]}_file_name", "#{params[:image_id]}_content_type", "#{params[:image_id]}_file_size", "#{params[:image_id]}_updated_at")
      activity.try(params[:image_id]).reprocess!
      if activity.valid?
        activity.transaction do
          activity.save
        end
        set_json_success({url: activity.try(params[:image_id]).url(:medium)})
      else
        set_json_error({message: activity.errors.full_messages.join(",")})
      end
    end

    respond_to do |format|
      format.json { render_to_json }
    end
  end
end

app/controllers/home/brand_controller.rb
class Home::BrandController < HomeController

  before_action :check_login

  def new
    @brand = Brand.new

    if request.post?
      @brand.attributes = brand_form_params
      if @brand.valid?
        @brand.save
        UserBrand.create(user_id: current_user.id, brand_id: @brand.id)
        redirect_to controller: "/home/brand", action: "list", type: Brand::HAVE_BIND
      else
        p @brand.errors
      end
    end
  end

 ##品牌列表
  def list
    @type = params[:type].blank? ? Brand::HAVE_BIND : params[:type].to_i
    @brands = Brand.get_brands(current_user.id, @type)
  end

  ##绑定品牌
  def operate
    data = {status: -1}
    if request.xhr?
      brand_id = params[:brand_id]
      user_id = current_user.id
      type = params[:type]

      max_count = 20

      user_brand = UserBrand.where(user_id: user_id, brand_id: brand_id).first
      ##解除绑定 type=1
      if type.to_i == Brand::HAVE_BIND
        if user_brand.blank?
          data[:status] = -1 ##解除失败
        else
          user_brand.destroy
          data[:status] = 1 ##解除成功
        end
      else
        if user_brand.blank?
          count = UserBrand.where(user_id: user_id, brand_id: brand_id).count
          if count < max_count
            user_brand = UserBrand.create(user_id: user_id, brand_id: brand_id)
            data[:status] = 2 ##绑定成功
          else
            data[:status] = 0 ##绑定失败，超过数目
          end
        else
          data[:status] = -1 ##绑定失败
        end
      end
    end
    return render_to_json(data)
  end


  def brand_form_params
    params.require(:brand)
        .permit(:user_id,
                :name,
                :logo,
                :brand_category_id,
                :province,
                :city,
                :district,
                :detail_address,
                :leader,
                :tel,
                :licence,
                :business_scope,
                :content
        )
  end
  private :brand_form_params

end

app/controllers/home/post_controller.rb
class Home::PostController < HomeController

  def index

  end

  def list
    @head_title = "我的展示"
    @posts = Post.where(check_flag: Post::EDIT_FLAG, user_id: current_user.id)
  end

  def new
    if params[:id].blank?
      @head_title = "新建活动"
      @post = Post.find_or_create_by(check_flag: Post::NEW_FLAG, user_id: current_user.id)
    else
      @head_title = "编辑活动"
      @post = Post.find_by(id: params[:id])
    end
    @brands = UserBrand.includes(:brand).where(user_id: current_user.id).map(&:brand)
    if request.post?
      @post.attributes = params.require(:post).permit(:title, :building, :province, :city, :district, :detail_address, :room_cnt, :living_room_cnt, :toilet_cnt, :kitchen_cnt, :home_size, :content1, :content2, :content3, :brand_ids)
      @post.check_flag = Post::EDIT_FLAG
      if !@post.valid?
        flash[:notice] = @post.errors.full_messages
        p flash[:notice]
      else
        @post.save
        return redirect_to home_post_list_path
      end
    end
  end

  def change_flag

  end

  def delete
    post = Post.find_by(id: params[:id], user_id: current_user.id)
    post.delete
    return redirect_to home_post_list_path
  end

  def upload_image
    if params[:image_id].blank? || params[:post_id].blank?
      set_json_error({message: "params error"})
    else
      post = Post.find_by(id: params[:post_id])
      post.attributes = params.require(:post).permit(params[:image_id], "#{params[:image_id]}_file_name", "#{params[:image_id]}_content_type", "#{params[:image_id]}_file_size", "#{params[:image_id]}_updated_at")
      post.try(params[:image_id]).reprocess!
      if post.valid?
        post.transaction do
          post.save
        end
        set_json_success({url: post.try(params[:image_id]).url(:medium)})
      else
        set_json_error({message: post.errors.full_messages.join(",")})
      end
    end

    respond_to do |format|
      format.json { render_to_json }
    end
  end
end

app/controllers/home/upload_controller.rb
class Home::UploadController < HomeController

  protect_from_forgery except: :create

  def create
    _style = params[:style].blank? ? 'original' : params[:style]
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.valid?
        @upload.save

        format.json { render :json => { url: @upload.image.url(_style), upload_id: @upload.id } }
      else
        format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
      end
    end
  end

  def update
    upload_id = params[:id]

    @upload = Upload.find_by_id(upload_id)

    if @upload.nil?
      @upload = Upload.new(upload_params)
      # format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
    else
      @upload.attributes = upload_params
      @upload.image.reprocess!
    end

    respond_to do |format|
      if @upload.valid?
        @upload.save
        format.json { render :json => { url: @upload.image.url(:original), upload_id: @upload.id } }
      else
        format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
      end
    end
  end

  # def create_avatar
  #   upload_type = params[:upload_type]
  #   blog_user_id = params[:id]
  #
  #   if upload_type == "blog_user" && blog_user_id.blank?
  #     blog_user_id = 0
  #   end
  #
  #   #获取Upload表存储存的文件ID
  #   blog_user = BlogUser.find_by_id(blog_user_id)
  #
  #   @upload = blog_user.get_avatar if !blog_user.blank?
  #
  #   if @upload.nil?
  #     @upload = Upload.new(upload_params)
  #     @upload.upload_type = upload_type
  #   else
  #     @upload.attributes = upload_params
  #     @upload.upload_type = upload_type
  #     @upload.image.reprocess!
  #   end
  #
  #   respond_to do |format|
  #     if @upload.valid?
  #       Upload.transaction do
  #         @upload.save
  #
  #         if !blog_user.blank?
  #           blog_user.avatar = @upload.id
  #           blog_user.save!
  #         end
  #       end
  #
  #       format.json { render :json => { url: @upload.image.url(:large), upload_id: @upload.id } }
  #     else
  #       format.json { render :json => { :errors => @upload.errors.full_messages }, :status => 422 }
  #     end
  #   end
  # end

  private

  def upload_params
    params.require(:upload).permit(:image, :image_file_name, :image_content_type, :image_file_size, :image_updated_at, :md5, :upload_type)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_login#, except: :favorite

  def index
    @head_title = "我的页面"
  end

  def edit
    @head_title = "编辑"
    @user_profile = current_user.user_profile
    if request.post?
      @user_profile.attributes = params.require(:user_profile).permit(:user_name, :motto, :province, :city, :district, :detail_address)
      if !@user_profile.valid?
        flash[:notice] = @user_profile.errors.full_messages
        p flash[:notice]
      end
      @user_profile.save
    end
  end

  def upload_image
    up = UserProfile.find_by(user_id: current_user.id)

    up.attributes = params.require(:user_profile).permit(:avatar, :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at)
    up.avatar.reprocess!

    respond_to do |format|
      if up.valid?
        up.transaction do
          up.save
        end
        set_json_success({url: up.avatar.url(:medium)})
      else
        set_json_error({message: up.errors.full_messages.join(",")})
      end
      format.json { render_to_json }
    end
  end

  def favorite
    uf = UserFavorite.find_by(user_id: current_user.id, post_id: params[:id])
    if uf.nil?
      UserFavorite.create(user_id: current_user.id, post_id: params[:id])
      set_json_success({value: "add"})
    else
      uf.delete
      set_json_success({value: "delete"})
    end

    respond_to do |format|
      format.json { render_to_json }
    end
  end

  private
  def check_login
    if !logged_in?
      redirect_to login_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def show_post_btn(post)
    if post.is_edit?
      link_to "公开", {controller: "/home/post", action: "change_flag", id: post.id, flag: Post::PUB_FLAG}, remote: true
    elsif post.is_pub?
      link_to "私有", {controller: "/home/post", action: "change_flag", id: post.id, flag: Post::EDIT_FLAG}, remote: true
    end
  end
end

app/views/home/activity/list.html.erb
<div class="md_card">
  <div class="md_box">
    <div class="post_new">
      <div class="post_btn">
        <%= link_to "发布活动", home_activity_new_path%>
      </div>
      <div class="post_brand">
        <p class="post_brand_title">品牌：</p>
        <div class="state">
          <span>状态：</span>
          <%#=link_to "已完成", {controller: :home, action: :list, flag: Post::PUB_FLAG}, {method: :post}%>
          <span class="state_a active"></span>
          <span class="state_b">草稿</span>
        </div>
      </div>
    </div>
    <%@activities.each do |activity|%>
        <div class="post_info">
          <div class="post_detail clearfix">
            <div class="post_pic" onclick="window.location.href='<%=activity_path(activity)%>'">
              <%=image_tag activity.get_avatar_img(:medium)%>
            </div>
            <div class="post_title">
              <span class="pic_title"><%=link_to activity.title, activity_path(activity)%></span>
              <span class="post_time"><%=activity.updated_at.to_s()%></span>
            </div>
            <div class="post_sub">
              <%#=show_post_btn(post)%>
              <%=link_to "编辑", home_activity_edit_path(activity)%>
              <%#=link_to "删除", home_post_delete_path(post), {method: :delete, data: {confirm: "确定删除?"},}%>
            </div>
          </div>
        </div>
    <%end%>
  </div>
</div>

app/views/home/activity/new.html.erb
<div class="release_activity">
  <%=form_for @activity, url: home_activity_new_path, method: "post" do |f|%>
      <%= hidden_field_tag(:id, params[:id]) %>
  <div class="release_area">
    <div class="release_pic">
      <%=image_tag @activity.get_avatar_img(:medium), id:"avatar1", width:"100%", height: "135px", onclick:"$('#file_avatar1').trigger('click')"%>
      <input type="file" id="file_avatar1" activity_id="<%=@activity.id%>" onchange="uploadActivityImage(this)" style="display: none">
    </div>
    <div class="release_text">
      <div class="input_a">
        <span class="icon-star-empty"></span>
        <%=f.text_field :title, class: "text", required: true, placeholder: "活动名称（必填）"%>
      </div>
    </div>
  </div>
  <div class="release_detail">
    <div class="release_detail_1">
      <div class="input_a">
        <span class="icon-star-empty"></span>
        <%=f.text_field :start_time, class: "text", id:"start_time", required: true, placeholder: "活动现场-开始时间（必填）"%>
      </div>
      <div class="input_a">
        <span class="icon-star-empty"></span>
        <%=f.text_field :end_time, class: "text", id:"end_time", required: true, placeholder: "活动现场-结束时间（必填）"%>
      </div>
      <div class="input_a" onclick="showModel('model_address')">
        <span class="icon-star-empty"></span>
        <input id="tmp_address" placeholder="活动地址（必填）" value="<%=@activity.get_address%>" required="true" class="text" type="text">
        <%= hidden_field :activity, :province, value: @activity.province, id: "province"%>
        <%= hidden_field :activity, :city, value: @activity.city, id: "city"%>
        <%= hidden_field :activity, :district, value: @activity.district, id: "district"%>
        <%= hidden_field :activity, :detail_address, value: @activity.detail_address, id: "detail_address"%>
      </div>
      <div class="input_a">
        <span class="icon-star-empty"></span>
        <%=f.text_field :phone, class: "text", required: true, placeholder: "咨询电话（必填）"%>
      </div>
    </div>
  </div>
  <div class="release_btn">
    <div class="add_info_btn" id="avatar2_addbtn" style="<%=@activity.check_img("avatar2")? '':'display:none'%>" onclick="addInfoBtn(this)">
      <span class="icon-cog"></span>
      <span>添加内容</span>
    </div>
    <%=image_tag @activity.get_avatar_img(:medium, "avatar2"), {id:"avatar2", width:"100%", height: "135px", onclick:"$('#file_avatar2').trigger('click')", style: @activity.check_img("avatar2")? 'display:none':''}%>
    <input type="file" id="file_avatar2" activity_id="<%=@activity.id%>" onchange="uploadActivityImage(this)" style="display: none">

    <div class="release_post">
      <a href="javascript:;" onclick="$('form').submit()">立即发布</a>
    </div>
  </div>
  <%end%>
</div>